[package]
name = "bulk_7z_extract"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
compress-tools = "0.12.2"
zstd = "0.9.0+zstd.1.5.0"